INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('김대중컨벤션센터', '제3전시장 하역장', '광주광역시', '연중무휴', 'No', 2, 0, 'No', 35.1467783223, 126.8404826732, '광주광역시 서구 상무누리로 30');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('김대중컨벤션센터', '지하주차장', '광주광역시', '연중무휴', 'DC차데모+AC3상+DC콤보', 1, 1, 'Yes', 35.1467783223, 126.8404826732, '광주광역시 서구 상무누리로 30');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('광주광역시 북구 양산동주민센터', '민원인주차장', '광주광역시', '연중무휴', 'DC차데모+AC3상+DC콤보', 0, 1, 'No', 35.209144, 126.879659, '광주광역시 북구 양산택지로 32');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('광주광역시 북구 문흥2동행정복지센터', '유료공영주차장', '광주광역시', '연중무휴', 'No', 1, 0, 'Yes', 35.18432223, 126.9219174, '광주광역시 북구 문산로 25');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('광주광역시 북구청', '민원인주차장', '광주광역시', '연중무휴', 'AC3상+DC차데모+DC콤보', 0, 1, 'No', 35.174288, 126.9121086, '광주광역시 북구 우치로 77');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('광주광역시 서구청', '외부주차장', '광주광역시', '연중무휴', 'AC3상+DC차데모+DC콤보', 1, 1, 'No', 35.1529017, 126.8906068, '광주광역시 서구 경열로 33');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('롯데마트(월드컵)', '주차장', '광주광역시', '연중무휴', 'AC3상+DC차데모+DC콤보', 0, 1, 'Yes', 35.1329733, 126.8755729, '광주광역시 서구 금화로 240');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('DJ 센터', '주차장', '광주광역시', '연중무휴', 'AC3상+DC차데모+DC콤보', 4, 2, 'No', 35.146778, 126.8409323, '광주광역시 서구 상무누리로 30(치평동)');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('광주광역시청', '의회동주차장', '광주광역시', '연중무휴', 'AC3상+DC차데모+DC콤보', 14, 2, 'No', 35.1600999528, 126.851463, '광주광역시 서구 내방로 111');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('광주광역시 서구청', '주차장', '광주광역시', '연중무휴', 'No', 1, 0, 'No', 35.1529017, 126.8906068, '광주광역시 서구 경열로 33');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('아이플렉스', '아이플렉스', '광주광역시', '연중무휴', 'No', 1, 0, 'No', 35.14813695, 126.9258412, '광주광역시 동구 동계천로 150');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('학동 금호베스트빌', '학동 금호베스트빌', '광주광역시', '연중무휴', 'No', 1, 0, 'No', 35.13336538, 126.9386613, '광주광역시 동구 증심천로 88');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('광주광역시 동구청', '광주동구청', '광주광역시', '연중무휴', 'AC3상+DC차데모+DC콤보', 0, 1, 'Yes', 35.14614143, 126.9230951, '광주광역시 동구 서남로 1');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('(주)전남일보', '(주)전남일보', '광주광역시', '연중무휴', 'No', 1, 0, 'No', 35.15001956, 126.9210604, '광주광역시 동구 제봉로 137');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('국민체육센터', '국민체육센터', '광주광역시', '연중무휴', 'AC3상+DC차데모+DC콤보', 0, 1, 'No', 35.15231248, 126.9327427, '광주광역시 동구 필문대로205번길 17');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('동구문화센터', '동구문화센터', '광주광역시', '연중무휴', 'AC3상+DC차데모+DC콤보', 0, 1, 'No', 35.1285716, 126.9309302, '광주광역시 동구 남문로 646');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('송암동 주민센터', '송암동 주민센터 주차장', '광주광역시', '연중무휴', 'AC3상+DC차데모+DC콤보', 0, 1, 'No', 35.1115380296, 126.8771095817, '광주광역시 남구 송암로 66');

INSERT INTO CHARGER (CHARGER_NAME, CHARGER_LOCATION, CITY, CLOSED_DATES, FAST_CHARGE_TYPE, SLOW_NUM, FAST_NUM, PARKING_FEE, LAT, LON, ADDRESS)
VALUES ('광주광역시 북구청', '민원인주차장', '광주광역시', '연중무휴', 'AC3상+DC차데모+DC콤보', 0, 1, 'No', 35.174288, 126.9121086, '광주광역시 북구 우치로 77');